name: hello-world

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Angi Test
        run: echo "Lov u Angi!"  

  Angi-job:
    runs-on: ubuntu-latest
    steps:
      - name: you-step
        run: echo "Hello World!"
      - name: Arun Test
        run: echo "Lov u Angi!"        